replicaCount: 2

ports:
  - name: http
    containerPort: 80
    protocol: TCP

service:
  name: common
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
