{{- define "common.deployment" -}}
{{- $common := dict "Values" .Values.common -}}
{{- $noCommon := omit .Values "common" -}}
{{- $overrides := dict "Values" $noCommon -}}
{{- $noValues := omit . "Values" -}}
{{- with merge $noValues $overrides $common -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "common.name" . }}
    helm.sh/chart: {{ include "common.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "common.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "common.name" . }}
    spec:
      containers:
      - image: nginx:1.26
        name: {{ .Chart.Name }}
        ports:
          - containerPort: 80
        {{- if .Values.env }}
        env:
        {{- range $key, $val := .Values.env }}
          - name: {{ $key }}
            value: {{ $val }}
        {{- end }}
        {{- end }}
        {{- if .Values.envFromSecretRefs }}
        envFrom:
        {{- range .Values.envFromSecretRefs }}
          - secretRef:
              name: {{ . }}
        {{- end }}
        {{- end }}
        {{- if .Values.livenessProbe_enabled }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe_enabled }}
        readinessProbe:
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
          - name: config
            mountPath: /etc/nginx/conf.d/
      volumes:
        - name: config
          configMap:
            name: {{ .Values.configmap.name }}

{{- end }}
{{- end }}
