server.port: 7002
spring.application.name: recommendation-service
server.error.include-message: always

logging:
  level:
    root: INFO
    com.example: DEBUG
---
spring.config.activate.on-profile: docker
server.port: 8080
