apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-ment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: nginx:1.26
        name: nginx
        ports:
        - containerPort: 80
