apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: replica-set
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: nginx:1.26
        name: nginx
        ports:
        - containerPort: 80
