apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "common.name" . }}
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "common.name" . }}
    spec:
      containers:
      - image: nginx:1.26
        name: {{ .Chart.Name }}
        #        name: {{ .Release.Service }}
        ports:
        - containerPort: 80
#        env:
#          - name: NAME
#            value: Oleg
#          - name: NAME_ADMIN
#            valueFrom:
#              secretKeyRef:
#                key: name1
#                name: tempsecret

        {{- if .Values.livenessProbe_enabled }}
        livenessProbe:
{{ toYaml .Values.livenessProbe | indent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe_enabled }}
{{ toYaml .Values.readinessProbe | indent 10 }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: config
          mountPath: /etc/nginx/conf.d/
      volumes:
      - name: config
        configMap:
          name: config-map
