apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  #  type: ClusterIP
  type: {{ .Values.service.type }}
  ports:
{{ toYaml .Values.service.ports | indent 4 }}
  selector:
    app: {{ include "common.name" . }}
