apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: {{ .Values.fullnameOverride }}
#  type: ClusterIP
  type: NodePort
